version: '3.9'
services:
  db:
    image: postgres:17
    container_name: lavecar-database
    ports:
      - '8765:6543'
      - '7654:5432'
    env_file:
      - .env
    volumes:
      - lavecar-data:/var/lib/postgresql/data/
  api:
    depends_on:
      - db
    build: .
    container_name: lavecar-backend
    ports:
      - 4041:3001
    env_file:
      - .env
volumes:
  lavecar-data:
